name: Publishing to NPM
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sushiswap'
          cache: 'yarn'
      - run: |
          yarn
          yarn test
          yarn build
          git config user.name GitHub Actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          yarn publish
          git add .
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
